blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/yourusername/aninotion-app/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issue
    url: https://github.com/yourusername/aninotion-app/security/advisories/new
    about: Report a security vulnerability privately